language: php 

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

notifications:
  email: false

sudo: enabled

#Compile
before_script:
    - openssl version -a
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script:
    - ./travis/run-test.sh
